# Application
spring.application.name=library-management-system

# Database Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/lms_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:kiit}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:change-me-in-production}

# Server
server.port=${PORT:8086}